from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol


class RealtimeMultimodalProvider(Protocol):
    async def connect(self) -> None: ...

    async def send_audio(self, pcm_bytes: bytes, timestamp_ms: int) -> None: ...

    async def send_frame(self, jpeg_bytes: bytes, timestamp_ms: int) -> None: ...

    async def finish_input(self) -> None: ...

    def events(self) -> AsyncIterator[dict[str, object]]: ...

    async def close(self) -> None: ...
